import { defineStore } from 'pinia'
import { ref, computed } from 'vue'

interface Product {
  id: number
  title: string
  price: number
  image: string
  category: string
  seller: string
  sellerId: number
  condition: string
  location: string
  createdAt: Date
  isFavorite: boolean
  description: string
  images: string[]
  brand?: string
}

export const useProductStore = defineStore('product', () => {
  const products = ref<Product[]>([
    {
      id: 1,
      title: 'iPhone 13 Pro',
      price: 450,
      image: '/product-1a.svg',
      category: 'Electrónica',
      seller: 'Juan Pérez',
      sellerId: 1,
      condition: 'Usado - Buen estado',
      location: 'Madrid',
      createdAt: new Date('2024-01-15'),
      isFavorite: false,
      description: 'iPhone 13 Pro en excelente estado',
      images: ['/product-1a.svg', '/product-1b.svg', '/product-1c.svg'],
      brand: 'apple',
    },
    {
      id: 2,
      title: 'MacBook Air M2',
      price: 800,
      image: '/product-2a.svg',
      category: 'Electrónica',
      seller: 'María García',
      sellerId: 2,
      condition: 'Nuevo',
      location: 'Barcelona',
      createdAt: new Date('2024-01-10'),
      isFavorite: false,
      description: 'MacBook Air M2 sin usar',
      images: ['/product-2a.svg', '/product-2b.svg', '/product-2c.svg'],
      brand: 'apple',
    },
    {
      id: 3,
      title: 'Samsung Galaxy S22',
      price: 380,
      image: '/placeholder.svg',
      category: 'Electrónica',
      seller: 'Lucia Ortiz',
      sellerId: 3,
      condition: 'Usado - Buen estado',
      location: 'Valencia',
      createdAt: new Date('2024-02-03'),
      isFavorite: false,
      description: 'Galaxy S22 con caja y cargador.',
      images: ['/placeholder.svg'],
      brand: 'samsung',
    },
    {
      id: 4,
      title: 'Nintendo Switch OLED',
      price: 260,
      image: '/placeholder.svg',
      category: 'Electrónica',
      seller: 'Diego Mora',
      sellerId: 4,
      condition: 'Usado - Como nuevo',
      location: 'Sevilla',
      createdAt: new Date('2024-02-08'),
      isFavorite: false,
      description: 'Con funda y dos mandos extra.',
      images: ['/placeholder.svg'],
    },
    {
      id: 5,
      title: 'Auriculares Sony WH-1000XM4',
      price: 170,
      image: '/placeholder.svg',
      category: 'Electrónica',
      seller: 'Paula Rey',
      sellerId: 5,
      condition: 'Usado - Buen estado',
      location: 'Bilbao',
      createdAt: new Date('2024-02-11'),
      isFavorite: false,
      description: 'Cancelacion de ruido y estuche.',
      images: ['/placeholder.svg'],
      brand: 'sony',
    },
    {
      id: 6,
      title: 'Seat Ibiza 2016',
      price: 7200,
      image: '/placeholder.svg',
      category: 'Vehículos',
      seller: 'Roberto Diaz',
      sellerId: 6,
      condition: 'Usado - Buen estado',
      location: 'Zaragoza',
      createdAt: new Date('2024-02-01'),
      isFavorite: false,
      description: 'ITV al dia, 120.000 km.',
      images: ['/placeholder.svg'],
      brand: 'seat',
    },
    {
      id: 7,
      title: 'Bicicleta urbana Orbea',
      price: 290,
      image: '/placeholder.svg',
      category: 'Vehículos',
      seller: 'Sara Gil',
      sellerId: 7,
      condition: 'Usado - Buen estado',
      location: 'Malaga',
      createdAt: new Date('2024-02-05'),
      isFavorite: false,
      description: 'Ideal ciudad, frenos revisados.',
      images: ['/placeholder.svg'],
    },
    {
      id: 8,
      title: 'Patinete Xiaomi Pro 2',
      price: 320,
      image: '/placeholder.svg',
      category: 'Vehículos',
      seller: 'Ivan Soto',
      sellerId: 8,
      condition: 'Usado - Como nuevo',
      location: 'Granada',
      createdAt: new Date('2024-02-07'),
      isFavorite: false,
      description: 'Bateria con buena autonomia.',
      images: ['/placeholder.svg'],
    },
    {
      id: 9,
      title: 'Moto Yamaha MT-07',
      price: 5200,
      image: '/placeholder.svg',
      category: 'Vehículos',
      seller: 'Nerea Vidal',
      sellerId: 9,
      condition: 'Usado - Buen estado',
      location: 'Alicante',
      createdAt: new Date('2024-02-09'),
      isFavorite: false,
      description: 'Revision reciente y neumáticos nuevos.',
      images: ['/placeholder.svg'],
    },
    {
      id: 10,
      title: 'Renault Clio 2018',
      price: 8900,
      image: '/placeholder.svg',
      category: 'Vehículos',
      seller: 'Adrian Torres',
      sellerId: 10,
      condition: 'Usado - Como nuevo',
      location: 'Valladolid',
      createdAt: new Date('2024-02-12'),
      isFavorite: false,
      description: 'Un solo dueño, historial completo.',
      images: ['/placeholder.svg'],
    },
    {
      id: 11,
      title: 'Chaqueta de cuero',
      price: 95,
      image: '/placeholder.svg',
      category: 'Moda',
      seller: 'Claudia Ramos',
      sellerId: 11,
      condition: 'Usado - Buen estado',
      location: 'Madrid',
      createdAt: new Date('2024-02-02'),
      isFavorite: false,
      description: 'Talla M, poco uso.',
      images: ['/placeholder.svg'],
    },
    {
      id: 12,
      title: 'Zapatillas Nike Air Max',
      price: 70,
      image: '/placeholder.svg',
      category: 'Moda',
      seller: 'Andrea Cruz',
      sellerId: 12,
      condition: 'Usado - Buen estado',
      location: 'Cordoba',
      createdAt: new Date('2024-02-04'),
      isFavorite: false,
      description: 'Talla 42, con caja.',
      images: ['/placeholder.svg'],
      brand: 'nike',
    },
    {
      id: 13,
      title: 'Bolso piel artesanal',
      price: 120,
      image: '/placeholder.svg',
      category: 'Moda',
      seller: 'Veronica Pardo',
      sellerId: 13,
      condition: 'Nuevo',
      location: 'Santander',
      createdAt: new Date('2024-02-06'),
      isFavorite: false,
      description: 'Cuero natural, acabado premium.',
      images: ['/placeholder.svg'],
    },
    {
      id: 14,
      title: 'Abrigo lana largo',
      price: 85,
      image: '/placeholder.svg',
      category: 'Moda',
      seller: 'Elena Marcos',
      sellerId: 14,
      condition: 'Usado - Como nuevo',
      location: 'Gijon',
      createdAt: new Date('2024-02-08'),
      isFavorite: false,
      description: 'Talla S, ideal invierno.',
      images: ['/placeholder.svg'],
    },
    {
      id: 15,
      title: 'Reloj minimalista',
      price: 60,
      image: '/placeholder.svg',
      category: 'Moda',
      seller: 'Mario Cano',
      sellerId: 15,
      condition: 'Usado - Buen estado',
      location: 'Pamplona',
      createdAt: new Date('2024-02-10'),
      isFavorite: false,
      description: 'Correa intercambiable.',
      images: ['/placeholder.svg'],
    },
    {
      id: 16,
      title: 'Sofa tres plazas',
      price: 350,
      image: '/placeholder.svg',
      category: 'Hogar',
      seller: 'Raquel Sanz',
      sellerId: 16,
      condition: 'Usado - Buen estado',
      location: 'Murcia',
      createdAt: new Date('2024-02-03'),
      isFavorite: false,
      description: 'Tapizado limpio y sin manchas.',
      images: ['/placeholder.svg'],
    },
    {
      id: 17,
      title: 'Mesa comedor extensible',
      price: 210,
      image: '/placeholder.svg',
      category: 'Hogar',
      seller: 'Oscar Glez',
      sellerId: 17,
      condition: 'Usado - Buen estado',
      location: 'Salamanca',
      createdAt: new Date('2024-02-05'),
      isFavorite: false,
      description: 'Madera maciza, incluye 6 sillas.',
      images: ['/placeholder.svg'],
    },
    {
      id: 18,
      title: 'Lampara de pie nordica',
      price: 55,
      image: '/placeholder.svg',
      category: 'Hogar',
      seller: 'Diana Ramos',
      sellerId: 18,
      condition: 'Nuevo',
      location: 'A Coruna',
      createdAt: new Date('2024-02-06'),
      isFavorite: false,
      description: 'Acabado metalico, luz calida.',
      images: ['/placeholder.svg'],
    },
    {
      id: 19,
      title: 'Cafetera espresso',
      price: 75,
      image: '/placeholder.svg',
      category: 'Hogar',
      seller: 'Tomas Rios',
      sellerId: 19,
      condition: 'Usado - Buen estado',
      location: 'Logrono',
      createdAt: new Date('2024-02-08'),
      isFavorite: false,
      description: 'Incluye accesorios y manual.',
      images: ['/placeholder.svg'],
    },
    {
      id: 20,
      title: 'Set vajilla 24 piezas',
      price: 40,
      image: '/placeholder.svg',
      category: 'Hogar',
      seller: 'Marta Alonso',
      sellerId: 20,
      condition: 'Usado - Buen estado',
      location: 'Toledo',
      createdAt: new Date('2024-02-10'),
      isFavorite: false,
      description: 'Porcelana blanca, sin roturas.',
      images: ['/placeholder.svg'],
    },
    {
      id: 21,
      title: 'Bicicleta de montaña',
      price: 420,
      image: '/placeholder.svg',
      category: 'Deportes',
      seller: 'Hugo Martin',
      sellerId: 21,
      condition: 'Usado - Buen estado',
      location: 'Oviedo',
      createdAt: new Date('2024-02-02'),
      isFavorite: false,
      description: 'Suspension delantera y frenos disco.',
      images: ['/placeholder.svg'],
    },
    {
      id: 22,
      title: 'Set mancuernas 20kg',
      price: 45,
      image: '/placeholder.svg',
      category: 'Deportes',
      seller: 'David Lago',
      sellerId: 22,
      condition: 'Usado - Buen estado',
      location: 'Burgos',
      createdAt: new Date('2024-02-04'),
      isFavorite: false,
      description: 'Incluye barras y discos.',
      images: ['/placeholder.svg'],
    },
    {
      id: 23,
      title: 'Tabla de surf 6.4',
      price: 260,
      image: '/placeholder.svg',
      category: 'Deportes',
      seller: 'Pablo Costa',
      sellerId: 23,
      condition: 'Usado - Buen estado',
      location: 'Cadiz',
      createdAt: new Date('2024-02-06'),
      isFavorite: false,
      description: 'Incluye funda y leash.',
      images: ['/placeholder.svg'],
    },
    {
      id: 24,
      title: 'Raqueta de tenis',
      price: 90,
      image: '/placeholder.svg',
      category: 'Deportes',
      seller: 'Cristina Mora',
      sellerId: 24,
      condition: 'Usado - Como nuevo',
      location: 'San Sebastian',
      createdAt: new Date('2024-02-08'),
      isFavorite: false,
      description: 'Wilson Pro Staff, encordada.',
      images: ['/placeholder.svg'],
    },
    {
      id: 25,
      title: 'Casco ciclismo',
      price: 35,
      image: '/placeholder.svg',
      category: 'Deportes',
      seller: 'Alba Lozano',
      sellerId: 25,
      condition: 'Nuevo',
      location: 'Tarragona',
      createdAt: new Date('2024-02-11'),
      isFavorite: false,
      description: 'Talla M, ventilado.',
      images: ['/placeholder.svg'],
    },
    {
      id: 26,
      title: 'Silla ergonomica',
      price: 140,
      image: '/placeholder.svg',
      category: 'Oficina',
      seller: 'Jose Molina',
      sellerId: 26,
      condition: 'Usado - Buen estado',
      location: 'Madrid',
      createdAt: new Date('2024-02-01'),
      isFavorite: false,
      description: 'Soporte lumbar ajustable.',
      images: ['/placeholder.svg'],
    },
    {
      id: 27,
      title: 'Monitor 27 pulgadas',
      price: 160,
      image: '/placeholder.svg',
      category: 'Oficina',
      seller: 'Sonia Perez',
      sellerId: 27,
      condition: 'Usado - Buen estado',
      location: 'Barcelona',
      createdAt: new Date('2024-02-03'),
      isFavorite: false,
      description: 'Full HD, panel IPS.',
      images: ['/placeholder.svg'],
    },
    {
      id: 28,
      title: 'Teclado mecanico',
      price: 65,
      image: '/placeholder.svg',
      category: 'Oficina',
      seller: 'Bruno Diaz',
      sellerId: 28,
      condition: 'Usado - Buen estado',
      location: 'Valencia',
      createdAt: new Date('2024-02-06'),
      isFavorite: false,
      description: 'Switches rojos, retroiluminado.',
      images: ['/placeholder.svg'],
    },
    {
      id: 29,
      title: 'Escritorio elevable',
      price: 220,
      image: '/placeholder.svg',
      category: 'Oficina',
      seller: 'Noelia Ruiz',
      sellerId: 29,
      condition: 'Usado - Buen estado',
      location: 'Sevilla',
      createdAt: new Date('2024-02-08'),
      isFavorite: false,
      description: 'Altura regulable, 120x60.',
      images: ['/placeholder.svg'],
    },
    {
      id: 30,
      title: 'Impresora laser',
      price: 85,
      image: '/placeholder.svg',
      category: 'Oficina',
      seller: 'Ismael Leon',
      sellerId: 30,
      condition: 'Usado - Buen estado',
      location: 'Castellon',
      createdAt: new Date('2024-02-12'),
      isFavorite: false,
      description: 'Incluye toner extra.',
      images: ['/placeholder.svg'],
    },
    {
      id: 31,
      title: 'Guitarra acustica',
      price: 150,
      image: '/placeholder.svg',
      category: 'Musica',
      seller: 'Manuel Herrera',
      sellerId: 31,
      condition: 'Usado - Buen estado',
      location: 'Cordoba',
      createdAt: new Date('2024-02-04'),
      isFavorite: false,
      description: 'Yamaha F310, con funda.',
      images: ['/placeholder.svg'],
    }
  ])

  const favorites = ref<number[]>([])
  const searchQuery = ref<string>('')
  const selectedCategory = ref<string>('')

  const filteredProducts = computed(() => {
    return products.value.filter((product) => {
      const matchesSearch = product.title
        .toLowerCase()
        .includes(searchQuery.value.toLowerCase())
      const matchesCategory =
        !selectedCategory.value || product.category === selectedCategory.value
      return matchesSearch && matchesCategory
    })
  })

  const getProductById = (id: string | number): Product | undefined => {
    return products.value.find((p) => p.id === Number(id))
  }

  const toggleFavorite = (productId: number): void => {
    const product = products.value.find((p) => p.id === productId)
    if (product) {
      product.isFavorite = !product.isFavorite
      if (product.isFavorite) {
        favorites.value.push(productId)
      } else {
        favorites.value = favorites.value.filter((id) => id !== productId)
      }
    }
  }

  const addProduct = (newProduct: Omit<Product, 'id' | 'isFavorite' | 'createdAt'>): void => {
    const id = Math.max(...products.value.map((p) => p.id), 0) + 1
    products.value.push({
      id,
      ...newProduct,
      isFavorite: false,
      createdAt: new Date(),
    })
  }

  const getProductsBySeller = (sellerId: number): Product[] => {
    return products.value.filter((p) => p.sellerId === sellerId);
  };

  return {
    products,
    favorites,
    searchQuery,
    selectedCategory,
    filteredProducts,
    getProductById,
    toggleFavorite,
    addProduct,
    getProductsBySeller,
  }
})
